apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-vol
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   # does not delete the data even after the pod is terminated or detached
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-064cb68c14853d9ce
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: static-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeName: static-vol
#   storageClassName: ""
#   resources:
#     requests:
#       storage: 20Gi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: pv-pod
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: pod-vol
#       mountPath: /usr/share/nginx/html
#   volumes:
#   - name: pod-vol
#     persistentVolumeClaim:
#       claimName: static-pvc
#   nodeSelector:
#     topology.kubernetes.io/zone: ap-south-2a