apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-vol
spec:
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0447b3f0482d10906
