apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticvol
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  csi:
    fsType: ext4
  volume:
    volume_nem: ebs
  storageClassName: standrard