apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    name: annotations
    key: value
    # Annotation
  annotations:
    github.com: "github.com/srikanth-suthari"
spec:
  containers:
    - name: container1
      image: nginx
    - name: container2
      image: almalinux:9
      command: ["sleep", "1000"]