apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  username: "srikanth"
  password: "srikanth@123"
  db_host_name: "mongodb"
  db_host_pass: "srikanth@123"
  payment_host: "roboshop"
  payment_pass: "roboshop@123"
