apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  selector:
    name: my-dep
    type: backend
    env: test
  type: NodePort
  ports:
    - protocol: TCP
      port: 90
      targetPort: 80