apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-dep
      type: backend
      env: test
  template:
    metadata:
      name: my-deployment-pods
      labels:
        name: my-dep
        type: backend
        env: test
    spec:
      containers:
        - name: httpd
          image: httpd

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: demo-svc-deployment
spec:
  type: LoadBalancer
  selector:
    name: my-dep
    type: backend
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80