apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop-dev
    region: us-east-1
managedNodeGroups:
  - name: roboshop-dev

    # type of instances
    instanceTypes: ["t3.small"]
    #desiredCapacity: 1 #  by default this value is 3
    spot: true  # Here we are using spot instances for our practice purpose