apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop
    region: us-east-1
managedNodeGroups:
  - name: roboshop

    # type of instances
    instanceTypes: ["t3.small"]
    desiredCapacity: 2 #  by default this value is 3
    # but we are taking two instances as our kubernetes worker nodes
    spot: true  # Here we are using spot instances for our practice purpose
