apiVersion: v1
kind: Pod
metadata:
  name: pod-errors
  labels:
    name: errors
    env: dev
spec:
  containers:
    - name: nginx
      # imagepullbackoff
      image: nginxx
    - name: almalinux
       # crashloopbackoff
      image: almalinux:9
