apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    name: my-app
    env: prod
    type: testing
    key: value
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "1000"]