apiVersion: v1
kind: Pod
metadata:
  name: liveness&readiness-demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       -  containerPort: 80
      livenessProbe:
        httpGet:
          path: /health    # Endpoint for liveness check
          port: 80
        initialDelaySeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        failureThreshold: 3
