apiVersion: v1
kind: Service
metadata:
  name: np-svc
spec:
  type: NodePort
  selector:
    name: pod-np
    type: nodeport
    env: dev-np
  ports:
  - protocol: TCP
    port: 90 #This is the service port
    # for nodeport we can mention the target port between 30000-32767 range
    # if we don't mention the port number k8s will automatically assing a port for this service
