apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  labels:
    name: pod-config
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "1000"]
    envFrom:
    - configMapRef:
        name: configmap-demo