apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
  labels:
    name: pod-secrets
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "1000"]
      envFrom:
      - secretRef:
          name: secret-demo