apiVersion: v1
kind: Service
metadata:
  name: rs-svc
spec:
  selector:
    name: eg-rs
    env: prod
    type: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80