apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
  labels:
    name-1: limits
    name-2: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # A pod can use these resources, based on the allocation
      # If these resources are not enough, then the pod will start using the max limit from the limits
      requests:   # soft limit which is allocated for the pod
        cpu: "5m"
        memory: "10M"
      # If the requested resources are not enough, then the pod will use these resources from the limits additionally
      # At final a pod can reach to this limit of resource usage
      limits: # Hard limit which is allocated for the pod
        cpu: "10m"
        memory: "20M"