# Secrets in Kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
  labels:
    name: secrets
# All the values or data should be in encodeed form.
data:
  username: "U3Jpa2FudGgK"
  password: "c3Jpa2FudGhAMTIzCg=="
