apiVersion: v1
kind: Service
metadata:
  name: service-cip-demo
spec:
  selector:
    name: cip
    env: dev
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # this is the service port which exposes the application from the pod or our container.
      targetPort: 80 # this is the container port.
