apiVersion: v1
kind: Pod
metadata:
  name: taints
spec:
  containers:
    - name: nginx
      image: nginx
  # tolerations:
  #   - key: ubuntu
  #     operator: "Exists"
  #     effect: "NoSchedule"
  nodeSelector:
    name: control-plane